- id: js-beautify
  name: js-beautify
  entry: js-beautify
  language: node
  files: \.html$
  args: []
  additional_dependencies: ['js-beautify@1.13.0']
  minimum_pre_commit_version: 2.7.1
  description: "Runs `js-beautify`"
